name: Rust

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
    types: [opened, synchronize, ready_for_review, reopened]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add clippy
        uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          default: true
          components: clippy
      - run: |
          cargo clippy --release --all-features --all-targets --workspace

  rust_fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add rustfmt
        uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          default: true
          components: rustfmt
      - run: |
          cargo fmt -- --check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cargo test
